{% set name = "dftbplus" %}
{% set version = "21.2" %}
{% set build = 1 %}
{% set mpi = mpi or "nompi" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: e73aa698ff951b59f7fe2ea027b292bae16abf545c9fdbb11b5b5127f04a3c10
  patches:
    - cmake.patch

{% if mpi == "nompi" %}
{% set build = build + 100 %}
{% endif %}
build:
  number: {{ build }}
  skip: True  # [win]

  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"

  {% if mpi != "nompi" %}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
  {% endif %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - fypp
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - {{ mpi }}  # [mpi != "nompi"]
    - mpifx * mpi_{{ mpi }}_*  # [mpi != "nompi"]
    - scalapack  # [mpi != "nompi"]
    - scalapackfx * mpi_{{ mpi }}_*  # [mpi != "nompi"]
    - elsi * mpi_{{ mpi }}_*  # [mpi != "nompi"]
    - libnegf * {{ mpi_prefix }}_*
    - arpack  # [mpi == "nompi"]
    - mctc-lib
    - simple-dftd3
    - libmbd * {{ mpi_prefix }}_*
    - plumed * {{ mpi_prefix }}_*
    - chimes-calculator
    - libblas
    - liblapack
  run:
    - {{ mpi }}  # [mpi != "nompi"]
    - {{ pin_compatible('mpifx', max_pin='x.x') }} mpi_{{ mpi }}_*  # [mpi != "nompi"]
    - scalapack  # [mpi != "nompi"]
    - {{ pin_compatible('scalapackfx', max_pin='x.x') }} mpi_{{ mpi }}_*  # [mpi != "nompi"]
    - {{ pin_compatible('elsi', max_pin='x.x') }} mpi_{{ mpi }}_*  # [mpi != "nompi"]
    - {{ pin_compatible('libnegf', max_pin='x.x') }} {{ mpi_prefix }}_*
    - arpack  # [mpi == "nompi"]
    - {{ pin_compatible('mctc-lib', max_pin='x.x') }} *
    - {{ pin_compatible('simple-dftd3', max_pin='x.x') }} *
    - {{ pin_compatible('libmbd', max_pin='x.x') }} {{ mpi_prefix }}_*
    - {{ pin_compatible('plumed', max_pin='x.x') }} {{ mpi_prefix }}_*
    - {{ pin_compatible('chimes-calculator', max_pin='x.x') }}

test:
  requires:
    - pkg-config
  commands:
    - export OMPI_MCA_plm=isolated OMPI_MCA_btl_vader_single_copy_mechanism=none OMPI_MCA_rmaps_base_oversubscribe=yes  # [mpi == "openmpi"]
    - pkg-config {{ name }} --exact-version {{ version }}
    - test -f $PREFIX/bin/dftb+
    - $PREFIX/bin/dftb+ | grep "No input file"  # [mpi == "nompi" and build_platform == target_platform]
    - mpiexec $PREFIX/bin/dftb+ | grep "No input file"  # [mpi != "nompi" and build_platform == target_platform]
    - test -f $PREFIX/lib/libdftbplus${SHLIB_EXT}

about:
  home: https://{{ name }}.org
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - "LICENSE"
    - "COPYING"
    - "COPYING.LESSER"
    - "external/fsockets/LICENSE"
    - "external/mudpack/LICENSE"
    - "external/xmlf90/LICENSE"
  summary: "DFTB+ general package for performing fast atomistic simulations"
  doc_url: https://{{ name }}-recipes.readthedocs.io
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - aradi
    - awvwgk
    - bhourahine
